name: flutter_book
description: flutter_book
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.5  
  scoped_model: ^2.0.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.0.0
  sqflite_common_ffi_web: ^0.4.5+4
  path_provider: ^2.1.5
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_calendar_carousel: ^2.4.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:  
    sdk: flutter

flutter:
  uses-material-design: true
